### ISSUE TITLE
npm version outdated?

### ISSUE THREAD

**Issue by benjamine** [tj/node-growl#57]
using growl inside mocha (depends on growl 1.8.1), I noticed the no-icon on OSX terminal-notifier, and tried to submit a PR, to my surprise I found that was done long time ago here:
https://github.com/tj/node-growl/commit/7136519582585f11ef5c6d92aab9b3a1c667c25c

is it possible that the last version published in npm (1.8.1) is not in sync with the last version in this repo? (actually I see npm says that was published 2 years ago https://www.npmjs.com/package/growl )

**Comment by jbnicolai** [comment]
:+1: I've published a new release to https://npmjs.org/package/growl. Enjoy!

**Comment by benjamine** [comment]
awesome!, thanks
